name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Cache Dependencies
        run: make cache
      - name: Run Tests
        run: make test
      # - name: Run Integration
      #   run: make int
      - name: Upload lib
        uses: actions/upload-artifact@v2.1.4
        with:
          path: lib
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.4
      - name: Cache Dependencies
        run: make cache
      - name: Run Linter
        run: make lint
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    steps:
    - name: Setup Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: github.event_name == 'pull_request'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: typescript
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [test, lint]
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Tag Repo
        run: make tag

