name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest # runs a test on Ubuntu, Windows and macOS
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
      - name: Cache Dependencies
        run: make cache
      - name: Run Tests
        run: make test
      - name: Upload lib
        uses: actions/upload-artifact@v2.1.4
        with:
          path: lib
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: 1.4
      - name: Cache Dependencies
        run: make cache
      - name: Run Linter
        run: make lint
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: github.event_name == 'pull_request'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: typescript
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

